### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by jing341** [zipperdev/Nomadcoffee-Backend#1]
What is this doing?

**Comment by zipperdev** [comment]
Umm...
Nomad Coders Instagram cloning challenge project
Yeah

**Comment by zipperdev** [comment]
I'm doing Assignment 3
It's little bit hard, but it's fun 😃

**Comment by jing341** [comment]
Why do you even use Github to do the Challenge?

**Comment by zipperdev** [comment]
Ya
On Instagram challenge, we use github.
And we submit github commit link :D
